[package]
name = "bobyard.io"
version = "0.0.1"

[dependencies]
Sui = { local = "/Users/yusong/works/rust/bobyard-sui/crates/sui-framework" }

[addresses]
bob =  "0x0"
sui =  "0000000000000000000000000000000000000002"
